---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: apt update
      apt: 
        update_cache: yes 
        cache_valid_time: 86400
      tags: [ 'packages' ]

- import_playbook: vpnserver.yml